class CancelledException(Exception):
    pass


class TimeoutException(Exception):
    pass
